---
kind: ConfigMap
apiVersion: v1
metadata:
  name: at-agent-ui-envs
  annotations:
    reloader.stakater.com/match: "true"
data:
  NEW_RELIC_APP_NAME: $(APP_NAME)-$(APP_ENV)
  NEW_RELIC_LOG_FILE_NAME: "STDOUT"
  NEW_RELIC_NO_CONFIG_FILE: "true"
