---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secrets
  annotations:
    reloader.stakater.com/match: "true"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: /global/infra/manual-common-keys
    - extract:
        key: /$(APP_NAME)/$(APP_ENV)/general-manual-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arcotech-registry
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: /global/infra/arcotech-docker-registry
