---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arcotech-docker-registry-api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      metadata:
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
          reloader.stakater.com/match: "true"
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: /global/infra/arcotech-docker-registry

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: at-agent-ui-secrets
  annotations:
    reloader.stakater.com/match: "true"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: at-agent-ui-secrets
  dataFrom:
    - extract:
        key: /$(APP_NAME)/$(APP_ENV)/general-manual-secrets


