---
varReference:
- kind: Ingress
  path: spec/tls/hosts
- kind: Ingress
  path: spec/tls/secretName
- kind: Ingress
  path: spec/rules/host
- kind: ConfigMap
  path: data
- kind: ExternalSecret
  path: spec/dataFrom/extract
- kind: EndpointMonitor
  path: spec/url
- kind: EndpointMonitor
  path: spec/uptimeRobotConfig/alertContacts
- kind: EndpointMonitor
  path: metadata/name
- kind: Deployment
  path: spec/template/spec/containers/livenessProbe/httpGet/path
- kind: Deployment
  path: spec/template/spec/containers/readinessProbe/httpGet/path
- kind: Ingress
  path: metadata/annotations