---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- external-secrets.yaml
- configmap.yaml
- deployment.yaml
- services.yaml  
- ingress.yaml
- uptimerobot.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: at-agent-ui-metadata

configurations:
  - kustomizeconfig.yaml

vars:
- name: APP_ENV
  objref:
    kind: ConfigMap
    name: at-agent-ui-metadata
    apiVersion: v1
  fieldref:
    fieldpath: data.APP_ENV
- name: APP_HOST
  objref:
    kind: ConfigMap
    name: at-agent-ui-metadata
    apiVersion: v1
  fieldref:
    fieldpath: data.APP_HOST
- name: PROJECT
  objref:
    kind: ConfigMap
    name: at-agent-ui-metadata
    apiVersion: v1
  fieldref:
    fieldpath: data.PROJECT
- name: APP_NAME
  objref:
    kind: ConfigMap
    name: at-agent-ui-metadata
    apiVersion: v1
  fieldref:
    fieldpath: data.APP_NAME
- name: UR_HEARTBEAT
  objref:
    kind: ConfigMap
    name: at-agent-ui-metadata
    apiVersion: v1
  fieldref:
    fieldpath: data.UR_HEARTBEAT
- name: HEALTH_CHECK
  objref:
    kind: ConfigMap
    name: at-agent-ui-metadata
    apiVersion: v1
  fieldref:
    fieldpath: data.HEALTH_CHECK
       