---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - overlays.yaml

configMapGenerator:
  - behavior: merge
    envs:
      - application.properties
      - infra.properties
    name: conf

patches:
  - target:
      kind: CronJob
    path: ./patches/endpointmonitor-patch.yaml
  - target:
      kind: Ingress
    path: ./patches/ingress-patch.yaml
