---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - overlays.yaml

configMapGenerator:
  - behavior: merge
    envs:
      - application.properties
      - infra.properties
    name: conf
