---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  io.arcotech.app: at-agent-ui

namespace: at-agent-ui

bases:
  - ../../base


configMapGenerator:
- behavior: merge
  envs:
  - .env
  name: at-agent-ui-metadata
